apiVersion: apps/v1
kind: Deployment
metadata:
  name: xygjbij
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xygjbij
  template:
    metadata:
      labels:
        app: xygjbij
    spec:
      containers:
      - image: okteto.dev/xygjbij:latest
        name: xygjbij
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4e783e3a-554f-40f3-bda6-cfb429ec51b1"
        - name: Vless_Path
          value: "/vl8t8yygy"
        - name: Vmess_UUID
          value: "4e783e3a-554f-40f3-bda6-cfb429ec51b1"
        - name: Vmess_Path
          value: "/vmti756dt"
        - name: Share_Path
          value: "/v2link"
